// Generated by scripts/build.mjs from src/client.js — do not edit this file.
// Browser half of dsh-macos-settings-shortcut. Executing this script only
// REGISTERS the lazy CJS factory; all behavior runs at materialization.
window.__ModuleLoader__.load({
	id: "dsh-macos-settings-shortcut",
	factory: (require) => {
		var module = { exports: {} };
		var exports = module.exports;
const name = "dsh-macos-settings-shortcut";

const inject = [];

const SETTINGS_LAUNCHER_SELECTOR = '[data-slot="settings.launcher"] button[aria-haspopup="menu"][aria-expanded]';

const SETTINGS_TRIGGER_SELECTOR = 'button[aria-haspopup="dialog"][aria-expanded]';

const SETTINGS_TRIGGER_SLOT_ANCHOR = '[data-slot="settings.trigger"]';

const SETTINGS_HEADER_SLOT_ANCHOR = '[data-slot="settings.header"]';

const SETTINGS_DIALOG_SELECTOR = '[role="dialog"][aria-modal="true"]';

const MENU_SELECTOR = '[role="menu"]';

const MENU_ITEM_SELECTOR = 'button[role="menuitem"]';

const MENU_DEADLINE_MS = 1000;

function isSettingsShortcut(event) {
	if (event === null || typeof event !== "object") return false;

	if (event.repeat) return false;
	if (event.isComposing) return false;

	if (!event.metaKey) return false;
	if (event.ctrlKey || event.altKey || event.shiftKey) return false;

	return event.key === "," || event.code === "Comma";
}

function isVisibleElement(element) {
	if (element === null || typeof element !== "object") return false;
	if (element.hidden === true) return false;
	if (element.disabled === true) return false;
	if (typeof element.getAttribute === "function") {
		if (element.getAttribute("hidden") !== null) return false;
		if (element.getAttribute("aria-hidden") === "true") return false;
	}
	const style = element.style;
	if (style !== null && typeof style === "object") {
		if (style.display === "none") return false;
		if (style.visibility === "hidden" || style.visibility === "collapse") return false;
	}
	if (typeof element.checkVisibility === "function" && element.checkVisibility() === false) return false;
	return true;
}

function carriesSlotAnchor(element, anchorSelector) {
	if (element === null || typeof element !== "object") return false;
	if (typeof element.querySelector !== "function") return false;
	return element.querySelector(anchorSelector) !== null;
}

function findSettingsLauncher(doc) {
	if (doc === null || typeof doc !== "object") return null;
	if (typeof doc.querySelectorAll !== "function") return null;
	const candidates = doc.querySelectorAll(SETTINGS_LAUNCHER_SELECTOR);
	const total = candidates === null || candidates === undefined || typeof candidates.length !== "number" ? 0 : candidates.length;
	for (let index = 0; index < total; index += 1) {
		const candidate = candidates[index];
		if (candidate === null || candidate === undefined) continue;
		if (typeof candidate.getAttribute !== "function") continue;
		if (typeof candidate.click !== "function") continue;
		if (isVisibleElement(candidate) === false) continue;
		return candidate;
	}
	return null;
}

function collectMenuRoots(doc) {
	const roots = [];
	if (doc === null || typeof doc !== "object") return roots;
	if (typeof doc.querySelectorAll !== "function") return roots;
	const menus = doc.querySelectorAll(MENU_SELECTOR);
	const total = menus === null || menus === undefined || typeof menus.length !== "number" ? 0 : menus.length;
	for (let index = 0; index < total; index += 1) {
		const menu = menus[index];
		if (menu === null || menu === undefined) continue;
		if (typeof menu.closest === "function" && menu.closest(MENU_SELECTOR) !== menu) continue;
		roots.push(menu);
	}
	return roots;
}

function isVisibleMenu(menu) {
	return isVisibleElement(menu);
}

function firstSelectableMenuItem(menu) {
	if (menu === null || typeof menu !== "object") return null;
	if (typeof menu.querySelectorAll !== "function") return null;
	const rows = menu.querySelectorAll(MENU_ITEM_SELECTOR);
	const total = rows === null || rows === undefined || typeof rows.length !== "number" ? 0 : rows.length;
	if (total === 0) return null;
	const first = rows[0];
	if (first === null || first === undefined) return null;
	if (typeof first.getAttribute !== "function") return null;
	if (typeof first.click !== "function") return null;
	if (first.getAttribute("aria-haspopup") === "menu") return null;
	if (first.getAttribute("aria-expanded") !== null) return null;
	if (isVisibleElement(first) === false) return null;
	return first;
}

function findSettingsDialog(doc) {
	if (doc === null || typeof doc !== "object") return null;
	if (typeof doc.querySelectorAll !== "function") return null;
	const dialogues = doc.querySelectorAll(SETTINGS_DIALOG_SELECTOR);
	const total = dialogues === null || dialogues === undefined || typeof dialogues.length !== "number" ? 0 : dialogues.length;
	for (let index = 0; index < total; index += 1) {
		const dialogue = dialogues[index];
		if (dialogue === null || dialogue === undefined) continue;
		if (carriesSlotAnchor(dialogue, SETTINGS_HEADER_SLOT_ANCHOR) === false) continue;
		return dialogue;
	}
	return null;
}

function collectCollapsedTriggers(doc) {
	const usable = [];
	if (doc === null || typeof doc !== "object") return usable;
	if (typeof doc.querySelectorAll !== "function") return usable;
	const candidates = doc.querySelectorAll(SETTINGS_TRIGGER_SELECTOR);
	const total = candidates === null || candidates === undefined || typeof candidates.length !== "number" ? 0 : candidates.length;
	for (let index = 0; index < total; index += 1) {
		const candidate = candidates[index];
		if (candidate === null || candidate === undefined) continue;
		if (typeof candidate.getAttribute !== "function") continue;
		if (typeof candidate.click !== "function") continue;

		if (candidate.getAttribute("aria-expanded") !== "false") continue;
		if (carriesSlotAnchor(candidate, SETTINGS_TRIGGER_SLOT_ANCHOR) === false) continue;
		if (isVisibleElement(candidate) === false) continue;
		usable.push(candidate);
	}
	return usable;
}

function findCollapsedTrigger(doc) {
	const usable = collectCollapsedTriggers(doc);
	return usable.length > 0 ? usable[0] : null;
}

function viewOf(doc) {
	if (doc !== null && typeof doc === "object" && doc.defaultView !== null && typeof doc.defaultView === "object") {
		return doc.defaultView;
	}
	return typeof globalThis === "undefined" ? undefined : globalThis;
}

function createFlowState() {
	return { pending: undefined };
}

function releasePending(state) {
	if (state === null || typeof state !== "object") return;
	const pending = state.pending;
	if (pending === undefined) return;
	state.pending = undefined;
	pending();
}

function startLauncherFlow(doc, launcher, state) {
	const existingMenus = new Set(collectMenuRoots(doc));
	const view = viewOf(doc);
	const flow = { observer: undefined, deadline: undefined, sawExpanded: false, settled: false };

	const settle = () => {
		if (flow.settled) return;
		flow.settled = true;
		if (flow.observer !== undefined) flow.observer.disconnect();
		if (flow.deadline !== undefined && view !== undefined && typeof view.clearTimeout === "function") {
			view.clearTimeout(flow.deadline);
		}
		if (state.pending === settle) state.pending = undefined;
	};

	const evaluate = () => {
		if (flow.settled) return true;

		if (launcher.getAttribute("aria-expanded") === "true") flow.sawExpanded = true;
		else if (flow.sawExpanded) {
			settle();
			return true;
		}
		const fresh = [];
		for (const menu of collectMenuRoots(doc)) {
			if (existingMenus.has(menu) === false) fresh.push(menu);
		}
		const visible = fresh.filter(isVisibleMenu);
		if (visible.length > 1) {

			settle();
			return true;
		}
		if (visible.length === 0) return false;
		const row = firstSelectableMenuItem(visible[0]);
		if (row === null) {

			settle();
			return true;
		}
		if (launcher.getAttribute("aria-expanded") !== "true") return false;
		row.click();
		settle();
		return true;
	};

	state.pending = settle;
	launcher.click();

	if (evaluate()) return;

	const body = doc.body;
	const Observer = view === undefined ? undefined : view.MutationObserver;
	if (typeof Observer === "function" && body !== null && typeof body === "object") {
		flow.observer = new Observer(() => {
			evaluate();
		});
		const options = {
			childList: true,
			subtree: true,
			attributes: true,
			attributeFilter: ["style", "hidden", "aria-hidden", "aria-expanded"]
		};
		try {
			flow.observer.observe(body, options);
		} catch {

			flow.observer = undefined;
		}
	}
	if (view !== undefined && typeof view.setTimeout === "function") {
		flow.deadline = view.setTimeout(() => {
			settle();
		}, MENU_DEADLINE_MS);
	} else {
		settle();
	}
}

function handleKeydown(event, doc, state) {
	if (isSettingsShortcut(event) === false) return false;
	if (typeof event.preventDefault !== "function") return false;
	const flowState = state === null || state === undefined || typeof state !== "object" ? createFlowState() : state;

	event.preventDefault();
	if (typeof event.stopPropagation === "function") event.stopPropagation();

	releasePending(flowState);

	if (findSettingsDialog(doc) !== null) return true;

	const launcher = findSettingsLauncher(doc);
	if (launcher !== null) {
		const expanded = launcher.getAttribute("aria-expanded");
		if (expanded === "false") {
			startLauncherFlow(doc, launcher, flowState);
			return true;
		}
		if (expanded === "true") {

			const visible = collectMenuRoots(doc).filter(isVisibleMenu);
			if (visible.length === 1) {
				const row = firstSelectableMenuItem(visible[0]);
				if (row !== null) row.click();
			}
		}
		return true;
	}

	const trigger = findCollapsedTrigger(doc);
	if (trigger !== null) trigger.click();
	return true;
}

function installSettingsShortcut(options) {
	const doc = options === null || options === undefined ? undefined : options.document;
	if (doc === null || doc === undefined || typeof doc.addEventListener !== "function") return null;
	const state = createFlowState();
	const listener = (event) => {
		handleKeydown(event, doc, state);
	};

	doc.addEventListener("keydown", listener, true);
	return function removeSettingsShortcutListener() {
		doc.removeEventListener("keydown", listener, true);
		releasePending(state);
	};
}

function apply(ctx) {
	ctx.effect(() => {
		const doc = typeof globalThis === "undefined" ? undefined : globalThis.document;
		const dispose = installSettingsShortcut({ document: doc });
		if (dispose === null) {
			ctx.logger?.warn?.("dsh-macos-settings-shortcut: no document available; Cmd+, is not installed");
			return undefined;
		}
		ctx.logger?.debug?.("dsh-macos-settings-shortcut: Cmd+, keydown listener installed");
		return dispose;
	}, "dsh-macos-settings-shortcut: keydown listener");
}

		exports.MENU_DEADLINE_MS = MENU_DEADLINE_MS;
		exports.MENU_ITEM_SELECTOR = MENU_ITEM_SELECTOR;
		exports.MENU_SELECTOR = MENU_SELECTOR;
		exports.SETTINGS_DIALOG_SELECTOR = SETTINGS_DIALOG_SELECTOR;
		exports.SETTINGS_HEADER_SLOT_ANCHOR = SETTINGS_HEADER_SLOT_ANCHOR;
		exports.SETTINGS_LAUNCHER_SELECTOR = SETTINGS_LAUNCHER_SELECTOR;
		exports.SETTINGS_TRIGGER_SELECTOR = SETTINGS_TRIGGER_SELECTOR;
		exports.SETTINGS_TRIGGER_SLOT_ANCHOR = SETTINGS_TRIGGER_SLOT_ANCHOR;
		exports.apply = apply;
		exports.carriesSlotAnchor = carriesSlotAnchor;
		exports.collectCollapsedTriggers = collectCollapsedTriggers;
		exports.collectMenuRoots = collectMenuRoots;
		exports.createFlowState = createFlowState;
		exports.findCollapsedTrigger = findCollapsedTrigger;
		exports.findSettingsDialog = findSettingsDialog;
		exports.findSettingsLauncher = findSettingsLauncher;
		exports.firstSelectableMenuItem = firstSelectableMenuItem;
		exports.handleKeydown = handleKeydown;
		exports.inject = inject;
		exports.installSettingsShortcut = installSettingsShortcut;
		exports.isSettingsShortcut = isSettingsShortcut;
		exports.isVisibleElement = isVisibleElement;
		exports.isVisibleMenu = isVisibleMenu;
		exports.name = name;
		return module.exports;
	}
});
