// Generated by scripts/build.mjs from src/client.js — do not edit this file.
// Browser half of dsh-macos-settings-shortcut. Executing this script only
// REGISTERS the lazy CJS factory; all behavior runs at materialization.
window.__ModuleLoader__.load({
	id: "dsh-macos-settings-shortcut",
	factory: (require) => {
		var module = { exports: {} };
		var exports = module.exports;
const name = "dsh-macos-settings-shortcut";

const inject = [];

const SETTINGS_TRIGGER_SELECTOR = 'button[aria-haspopup="dialog"][aria-expanded]';

const SETTINGS_TRIGGER_SLOT_ANCHOR = '[data-slot="settings.trigger"]';

function isSettingsShortcut(event) {
	if (event === null || typeof event !== "object") return false;

	if (event.repeat) return false;
	if (event.isComposing) return false;

	if (!event.metaKey) return false;
	if (event.ctrlKey || event.altKey || event.shiftKey) return false;

	return event.key === "," || event.code === "Comma";
}

function isVisibleTrigger(element) {
	if (element === null || typeof element !== "object") return false;
	if (element.hidden === true) return false;
	if (element.disabled === true) return false;
	if (typeof element.getAttribute === "function") {
		if (element.getAttribute("hidden") !== null) return false;
		if (element.getAttribute("aria-hidden") === "true") return false;
	}
	const style = element.style;
	if (style !== null && typeof style === "object") {
		if (style.display === "none") return false;
		if (style.visibility === "hidden" || style.visibility === "collapse") return false;
	}
	if (typeof element.checkVisibility === "function" && element.checkVisibility() === false) return false;
	return true;
}

function collectCollapsedTriggers(doc) {
	const usable = [];
	if (doc === null || typeof doc !== "object") return usable;
	if (typeof doc.querySelectorAll !== "function") return usable;
	const candidates = doc.querySelectorAll(SETTINGS_TRIGGER_SELECTOR);
	if (candidates === null || candidates === undefined) return usable;
	const total = typeof candidates.length === "number" ? candidates.length : 0;
	for (let index = 0; index < total; index += 1) {
		const candidate = candidates[index];
		if (candidate === null || candidate === undefined) continue;
		if (typeof candidate.getAttribute !== "function") continue;
		if (typeof candidate.click !== "function") continue;

		if (candidate.getAttribute("aria-expanded") !== "false") continue;
		if (isVisibleTrigger(candidate) === false) continue;
		usable.push(candidate);
	}
	return usable;
}

function carriesSettingsSlotAnchor(candidate) {
	if (candidate === null || typeof candidate !== "object") return false;
	if (typeof candidate.querySelector !== "function") return false;
	return candidate.querySelector(SETTINGS_TRIGGER_SLOT_ANCHOR) !== null;
}

function findCollapsedTrigger(doc) {
	const usable = collectCollapsedTriggers(doc);
	for (let index = 0; index < usable.length; index += 1) {
		if (carriesSettingsSlotAnchor(usable[index])) return usable[index];
	}
	return usable.length > 0 ? usable[0] : null;
}

function handleKeydown(event, doc) {
	if (isSettingsShortcut(event) === false) return false;
	if (typeof event.preventDefault !== "function") return false;

	event.preventDefault();
	if (typeof event.stopPropagation === "function") event.stopPropagation();
	const trigger = findCollapsedTrigger(doc);
	if (trigger === null) return true;
	trigger.click();
	return true;
}

function installSettingsShortcut(options) {
	const doc = options === null || options === undefined ? undefined : options.document;
	if (doc === null || doc === undefined || typeof doc.addEventListener !== "function") return null;
	const listener = (event) => {
		handleKeydown(event, doc);
	};

	doc.addEventListener("keydown", listener, true);
	return function removeSettingsShortcutListener() {
		doc.removeEventListener("keydown", listener, true);
	};
}

function apply(ctx) {
	ctx.effect(() => {
		const doc = typeof globalThis === "undefined" ? undefined : globalThis.document;
		const dispose = installSettingsShortcut({ document: doc });
		if (dispose === null) {
			ctx.logger?.warn?.("dsh-macos-settings-shortcut: no document available; Cmd+, is not installed");
			return undefined;
		}
		ctx.logger?.debug?.("dsh-macos-settings-shortcut: Cmd+, keydown listener installed");
		return dispose;
	}, "dsh-macos-settings-shortcut: keydown listener");
}

		exports.SETTINGS_TRIGGER_SELECTOR = SETTINGS_TRIGGER_SELECTOR;
		exports.SETTINGS_TRIGGER_SLOT_ANCHOR = SETTINGS_TRIGGER_SLOT_ANCHOR;
		exports.apply = apply;
		exports.carriesSettingsSlotAnchor = carriesSettingsSlotAnchor;
		exports.collectCollapsedTriggers = collectCollapsedTriggers;
		exports.findCollapsedTrigger = findCollapsedTrigger;
		exports.handleKeydown = handleKeydown;
		exports.inject = inject;
		exports.installSettingsShortcut = installSettingsShortcut;
		exports.isSettingsShortcut = isSettingsShortcut;
		exports.isVisibleTrigger = isVisibleTrigger;
		exports.name = name;
		return module.exports;
	}
});
